# -*- coding:utf-8 -*-
ELEMENT_TYPE = ["abc",
                "fbx",
                "ass",
                "gpu",
                "ma",
                "ms",
                "mb",
                "obj",
                "rs",
                "xarc",
                "hdr",
                "nk",
                "hip",
                "project",
                "source",
                ]
